# Logging Configuration for xetra project
version: 1
disable_existing_loggers: true
formatters:
  xetra:
    format: "%(asctime)s - %(levelname)s - %(message)s"
    datefmt: "%d-%b-%Y %H:%M:%S"
handlers:
  filehandler:
    class: logging.FileHandler
    formatter: xetra
    level: INFO
    filename: "Xetra Transformer.log"
    mode: "w"
  console:
    class: logging.StreamHandler
    formatter: xetra
    level: INFO
root:
  level: INFO
  handlers: [console, filehandler]